server:
  port: 28888

topic:
  catalogue:
    name: t.catalogue

backend:
  url: http://localhost:28889
  #url: http://backend-service:28889

keycloak:
  auth-server-url: http://127.0.0.1:8080/auth
  #auth-server-url: http://keycloak:8080/auth
  realm: "MCS"
  resource: "gateway-client"
  principal-attribute: preferred_username
  ssl-required: external
  credentials:
    secret: 7E9jsqJESTQMdGCp00UqLMcXpHEjGMUb
#  use-resource-role-mappings: true

spring:
  kafka:
    #bootstrap-servers: "kafka:9092"
    bootstrap-servers: "localhost:9093"
    consumer:
      auto-offset-reset: earliest
      group-id: "gateway"

logging:
  level:
    org:
      springframework:
        security: off