server:
  port: 28888

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/postgresDB
    url: jdbc:postgresql://postgres-container:5432/postgresDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest

logging:
  level:
    org:
      springframework:
        security: DEBUG