server:
  port: 28888

topic:
  catalogue:
    name: t.catalogue

backend:
  url: http://localhost:28889
  #url: http://backend-service:28889

keycloak:
  auth-server-url: http://localhost:8080/auth
  #auth-server-url: http://keycloak:8080/auth
  realm: "MCS"
  resource: "gateway-client"
  bearer-only: true
  security-constraints:
    - authRoles:
        - uma_authorization
      securityCollections:
        - patterns:
            - /*

spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresDB
#    #url: jdbc:postgresql://postgres-container-gateway:5432/postgresDB
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  kafka:
    #bootstrap-servers: "kafka:9092"
    bootstrap-servers: "localhost:9093"
    consumer:
      auto-offset-reset: earliest
      group-id: "gateway"

logging:
  level:
    org:
      springframework:
        security: off