server:
  port: 28888

topic:
  catalogue:
    name: t.catalogue

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDB
    #url: jdbc:postgresql://postgres-container-gateway:5432/postgresDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  kafka:
    #bootstrap-servers: "kafka:9092"
    bootstrap-servers: "localhost:9093"
    consumer:
      auto-offset-reset: earliest
      group-id: "default"

logging:
  level:
    org:
      springframework:
        security: DEBUG