server:
  port: 28889

topic:
  delivery:
    name: t.delivery
  order:
    name: t.order
  catalogue:
    name: t.catalogue


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgresDB
    #    url: jdbc:postgresql://postgres-container-backend:5433/postgresDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

  kafka:
    #    bootstrap-servers: "kafka:9092"
    bootstrap-servers: "localhost:9093"
    consumer:
      auto-offset-reset: earliest
      group-id: "default"