server:
  port: 28889

topic:
  delivery:
    name: t.delivery
  delivery-result:
    name: t.delivery-result
  order:
    name: t.order
  catalogue:
    name: t.catalogue
  amount:
    name: t.amount
  payment:
    name: t.payment
  category:
    name: t.category-wrapper


spring:
  datasource:
    #url: jdbc:postgresql://localhost:5433/postgresDB
    url: jdbc:postgresql://postgres-container-backend:5433/postgresDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: "kafka:9092"
    #bootstrap-servers: "localhost:9093"
    jaas:
      enabled: true
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: "backend"

keycloak:
  #auth-server-url: http://127.0.0.1:8080/auth  #there is only - 127.0.0.1:8080, not localhost:8080
  auth-server-url: http://keycloak:8080/auth
  realm: "MCS"
  resource: "backend-client"
  bearer-only: true
  ssl-required: external
  credentials:
    secret: super_secret_password_for_backend_service
  confidential-port: 0

logging:
  level:
    org:
      springframework:
        security: off
